### ISSUE TITLE
Номерът на секцията в протокола да е пълния единен секционен номер, а не само последните три

### ISSUE THREAD

**Issue by hkdobrev** [ti-broish/admin#29]
https://upravitel.tibroish.bg/protocol/01F2EFV99X85XN3N9X5BVJ4FQ6

<img width="784" alt="Screenshot_2021-04-05_at_22 51 04" src="https://user-images.githubusercontent.com/506129/114453476-3b9d2280-9be2-11eb-8b57-2ee92385f39c.png">

**Comment by koki7o** [comment]
Fixed
