### ISSUE TITLE
Контроли при валидиране

### ISSUE THREAD

**Issue by svilenzhelev** [ti-broish/admin#50]
## ХАРТИЕН

- [ ] Сумата на гласовете в секция РАЗПРЕДЕЛЕНИЕ НА ГЛАСОВЕТЕ ПО КАНДИДАТСКИ ЛИСТИ (включително "Не подкрепям никого") трябва да е равна на 7.1. Брой на действителните гласове, подадени за кандидатските листи на партии, коалиции и инициативни комитети
- [ ] Числото по т. 5 трябва да е равно на числото по т. 3. 

## МАШИНЕН

- [ ] Сумата на гласовете в секция РАЗПРЕДЕЛЕНИЕ НА ГЛАСОВЕТЕ ПО КАНДИДАТСКИ ЛИСТИ (включително "Не подкрепям никого") трябва да е равна на т. 5. Общ брой на потвърдените гласове.
- [ ] Числото по т. 5 трябва да е равно на числото по т. 3. 

## ХАРТИЕНО-МАШИНЕН

- [ ] Сумата на гласовете в КОЛОНИТЕ ЗА МАШИНИ (М) в секция РАЗПРЕДЕЛЕНИЕ НА ГЛАСОВЕТЕ ПО КАНДИДАТСКИ ЛИСТИ (включително "Не подкрепям никого") трябва да е равна на т. 5.2. Брой на потвърдените гласове от машинното гласуване
- [ ] Сумата на гласовете в КОЛОНА ХАРТИЯ (Х) в секция РАЗПРЕДЕЛЕНИЕ НА ГЛАСОВЕТЕ ПО КАНДИДАТСКИ ЛИСТИ (включително "Не подкрепям никого") трябва да е равна на т. 5.1. Брой на намерените в избирателните кутии бюлетини
- [ ] Числото по т. 5 трябва да е равно на числото по т. 3.

**Comment by hkdobrev** [comment]
Тези проверки вече са стари и валидните са в #67
